name: untitled
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.0
  http: ^0.13.5
  build_runner: ^2.2.1
  firebase_auth: ^3.10.0
  cloud_firestore: ^3.1.5
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_sign_in: ^5.4.2
  location: ^4.4.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
